#!/usr/sbin/nft -f

table inet filter {
	chain input {
		type filter hook input priority filter; policy accept;
		tcp dport 25550 tcp flags syn ct count over 5 reject with tcp reset
	}
}

table ip nat {
	chain input {
		type nat hook input priority 100;
		tcp dport 25550 snat to 10.131.0.0-10.131.255.255
		udp dport 19132 snat to 10.131.0.0-10.131.255.255
	}
}

table ip6 nat {
	chain input {
		type nat hook input priority 100;
		tcp dport 25550 snat to fdef:dead:af::1-fdef:dead:af::ffff
		udp dport 19132 snat to fdef:dead:af::1-fdef:dead:af::ffff
	}
}
